name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Ежедневно в 00:00
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync Fork
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.mergeUpstream({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main'
            })