name: Sync Upstream
on:
  push:
    branches: [ main ]
    workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Verify PAT
        run: |
          echo "Token first chars: ${PAT:0:4}"
          git remote -v
    
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge changes from upstream
        run: |

          git remote add upstream https://github.com/matrix-org/matrix-rust-sdk.git || true
          
          git fetch upstream main
          
          git merge --no-ff upstream/main
          
          git push https://${{ secrets.PAT }}@github.com/hek4ek/matrix-rust-sdk.git main

  notify:
    needs: merge
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: hek4ek/matrix-rust-components-swift
          event-type: rust-sdk-updated